name: Combined Workflow

on:
  push:
    branches:
      - **

jobs:
  run-tests-front:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger tests-front
      uses: ./.github/workflows/tests-front.yml


  run-integration-tests:
    needs: run-tests-front
    runs-on: ubuntu-latest
    steps:
    - name: Trigger integration tests
      run: ./.github/workflows/integration-tests.yml

  run-e2e-tests:
    needs: run-integration-tests
    runs-on: ubuntu-latest
    steps:
    - name: Trigger e2e-tests
      run: ./.github/workflows/e2e-tests.yml


  run-build-front:
    needs: run-e2e-tests
    runs-on: ubuntu-latest
    steps:
    - name: Trigger build front
      run: ./.github/workflows/build-front.yml